name: swag_time
description: Swag/Time — OSINT toolkit
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/icon.png"